### ISSUE TITLE
agenda.php

### ISSUE THREAD

**Issue by KurokiUrabe** [tavorazo/Clinic#16]
no entiendo por que están estos if, y que cuenta se supone estoy usando, me refiero si estoy en la cuenda de admin?

**Comment by tavorazo** [comment]
cuales if? si estas en la de admin :D

Como te decia la otra vez, tu enfocate en ahorita en las query va? se supone q no debe de tener problemaa pues ya estaba funcionando. Pero ajeno a eso, trata de terminar la issue de querys va? :) 

panel.php ya esta completo y bien. avisame que onda

**Comment by KurokiUrabe** [comment]
el panel si
estaba biendo por orden de menu registro de consulta y vi todos esos if para mostrar contenido solo para ciertos usuarios, la query ya funciona. pero al darle clic en un nombre y seleccionar fecha salen errores que estoy revisando.

**Comment by KurokiUrabe** [comment]
ya se que es jojojo un moustro

**Comment by tavorazo** [comment]
cuando se resuelva la duda arrastra a "done"

**Comment by KurokiUrabe** [comment]
yep
