### ISSUE TITLE
add-paciente.php

### ISSUE THREAD

**Issue by KurokiUrabe** [tavorazo/Clinic#21]
tavo en la forma add-paciente.php donde esta la entrada expediente?

**Comment by tavorazo** [comment]
no entiendo, haber dame más detalle. Estas en add-paciente, y que es lo que ocupas? :)

**Comment by KurokiUrabe** [comment]
bueno están todos esos input pero en nuevo-paciente solicita uno campo o dato por post que es expediente

**Comment by tavorazo** [comment]
este es el problema que deciamos verdad? el que se dejara nulo el campo

**Comment by tavorazo** [comment]
ya se soluciono?
