### ISSUE TITLE
seleccionar_paciente_final.php

### ISSUE THREAD

**Issue by KurokiUrabe** [tavorazo/Clinic#22]
Undefined variable: n_dia

**Comment by tavorazo** [comment]
moviste algo?

**Comment by tavorazo** [comment]
echo '<form action="seleccionar_paciente.php" method="POST" >
              <input type="hidden" value="',$dia,'" name="dia">
              <input type="hidden" value="',$n_dia,'" name="n_dia">
              <input type="hidden" value="',$mes_n,'" name="mes">
              <input type="hidden" value="',$ano,'" name="ano">
              <input type="hidden" value="',$hora,'" name="hora">
              <input type="hidden" value="',$minuto,'" name="minuto">
              <input type="hidden" value="',$doctor,'" name="doctor">
              <input type="submit" value="< Buscar otro paciente" 
                    style="width:200px; border-right:gray 1px solid; background:none; float:left;  color: gray">
            </form>';
