### ISSUE TITLE
subir.php

### ISSUE THREAD

**Issue by KurokiUrabe** [tavorazo/Clinic#30]
existe?

**Comment by tavorazo** [comment]
donde se supone que debe de estar?

**Comment by KurokiUrabe** [comment]
esta en Clinic\System\pacientes\ficha-paciente.php:

**Comment by tavorazo** [comment]
No esta :/ cual se supone que seria su función? caray con estos detalles....

**Comment by KurokiUrabe** [comment]
no se que funcion tiene solo te manda después de terminar en ese php
