### ISSUE TITLE
id paciente

### ISSUE THREAD

**Issue by KurokiUrabe** [tavorazo/Clinic#31]
donde puedo ver el id del paciente, necesito saber el id de cada paciente para cotejar con la búsqueda de pacientes

**Comment by tavorazo** [comment]
ammm por ejemplo, en panel.php estan impresos los id de esos pacientes. Por otro lado, existe una lista. Te agrego el link

http://endoperio.wbx.technology/pacientes/lista_pacientes2.php

**Comment by KurokiUrabe** [comment]
es como la base de datos?

**Comment by tavorazo** [comment]
esa lista? si es el select de los pacientes, y el id es la llave de c/paciente
