### ISSUE TITLE
Modificar felicitacion

### ISSUE THREAD

**Issue by tavorazo** [tavorazo/Clinic#46]
Checar la modificacion de la felicitacion

(ya salia antes de subirlo al server, se supone que en heroku sale)

**Comment by adrianVaNa** [comment]
La fuente de la imagen de felicitación era esta http://www.webox.org.mx/Proyectos/endoperio/images/feliz.png

pero no está disponible esa dirección por lo que la cambié a la misma imagen contenida en los archivos locales es decir sólo "/images/feliz.png"

**Comment by tavorazo** [comment]
si, que bueno que viste ese detalle.
