### ISSUE TITLE
Observaciones

### ISSUE THREAD

**Issue by tavorazo** [tavorazo/Clinic#47]
Descripcion= 

el numero de row que se cita en el query esta mal, es uno menos. 

link=

http://www.endoperio.com.mx/System/consultar_citas.php?ano=2016&mes=1&dia=5&n_dia=Martes

**Comment by adrianVaNa** [comment]
sólo hay que cambiar el número de row verdad?  según yo es el de las líneas 131 132

**Comment by tavorazo** [comment]
no tengo a la mano el numero de filas pero si, es eso... checas en la base
