### ISSUE TITLE
camara

### ISSUE THREAD

**Issue by tavorazo** [tavorazo/Clinic#48]
Descripci'on.

cambiar el script para ingresar a la camara

Link=
http://www.endoperio.com.mx/System/add-paciente.php

*el link donde se guardara la imagen es una de las cosas que faltan, receurda que te mencione que todas las fotos van en el servidor local.

**Comment by adrianVaNa** [comment]
Se agregó plugin para guardar imagenes desde cámara o archivo... Funciona bien en Heroku!!

**Comment by tavorazo** [comment]
creo que el problema puede ser del servidor
