### ISSUE TITLE
foto internas

### ISSUE THREAD

**Issue by tavorazo** [tavorazo/Clinic#53]
url archivo en servidor local

Aqui, en ficha de paciente es donde se agrega las fotos, puedes revisar los links para ver cuales son los archivos.

http://www.endoperio.com.mx/System/pacientes/ficha-paciente.php?id=2924

**Comment by adrianVaNa** [comment]
en la BD no hay una tabla para las fotografías clínicas, falta crearla.

**Comment by tavorazo** [comment]
SI es de esa forma, adelante. Solo checa que en verdad no exista.

**Comment by adrianVaNa** [comment]
si existe la tabla, las fotos ya son almacenadas en server y bd
