### ISSUE TITLE
Foto externa

### ISSUE THREAD

**Issue by tavorazo** [tavorazo/Clinic#54]
url archivo en servidor local

Aqui, en ficha de paciente es donde se agrega las fotos, puedes revisar los links para ver cuales son los archivos.

http://www.endoperio.com.mx/System/pacientes/ficha-paciente.php?id=2924

**Comment by adrianVaNa** [comment]
ya se suben las fotos externas al server, falta agregar los archivos a la bd

**Comment by adrianVaNa** [comment]
las fotos ya se guardan el la base y en el server local

**Comment by tavorazo** [comment]
entonces ya esta? o falta calarlo?

**Comment by adrianVaNa** [comment]
pues faltaría comprobar que sí está funcionando bien
