### ISSUE TITLE
migrar todas las fotos de server web al server local

### ISSUE THREAD

**Issue by tavorazo** [tavorazo/Clinic#56]

**Comment by adrianVaNa** [comment]
falta cambiar nombres de las imágenes desde la bd

**Comment by tavorazo** [comment]
ok, avisame cuando ya este

2016-02-08 13:24 GMT-06:00 adrianVaNa <notifications@github.com>:

> falta cambiar nombres de las imágenes desde la bd
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tavorazo/Clinic/issues/56#issuecomment-181462872>.
>



--
