### ISSUE TITLE
URGE correjir o rehacer el registro de pacientes

### ISSUE THREAD

**Issue by tavorazo** [tavorazo/Clinic#60]
corregir o rehacer archivo

System/add-paciente.php
System/php/nuevo_usuario.php

Flujo de trabajo
1. Form con validacion para ingresar los datos
2. PUT para ingresar los datos a la tabla PACIENTES
3. return GET vista de ficha de pacientes

Posible error:
Se agregaron renglones a las tablas entonces estoy seguro que existen cambios erroneos

**Comment by adrianVaNa** [comment]
El form de add-paciente indica que va hacia un archivo dentro de la carpeta \pacientes\images_pacientes\add-paciente.php y es un archivo similar... supongo que aquí está el error

**Comment by tavorazo** [comment]
si, te lo deje en el comentario no? bueno, si se supone que es el "backend" pero aquí es código basura, as'i que checalo ah'i

**Comment by adrianVaNa** [comment]
ok ya... probandolo localmente me agrega sin problemas... únicamente falta que se ingrese el form para la columna alergias... lo agrego?

**Comment by tavorazo** [comment]
en registro de pacientes no tiene la columna de alergias? si agregala porfa
