### ISSUE TITLE
URGE correjir editar paciente

### ISSUE THREAD

**Issue by tavorazo** [tavorazo/Clinic#61]
correjir o rehacer los archivos

System/pacientes/edit-paciente.php 
System/pacientes/procesar_editar.php

Flujo

1. GET para traer todos los datos de paciente
2. mostrarlos en el form
3. UPDATE para actualizar los cambios

Posible error:
Se agregaron renglones a las tablas entonces estoy seguro que existen cambos erroneos

**Comment by adrianVaNa** [comment]
el archivo de procesar recibe el POST de 'expediente' comenté la línea 39 para que no lo reciba... Revisando la tabla paciendes de la BD este valor se encuentra vacío para todos los pacientes

**Comment by tavorazo** [comment]
fijate de donde viene para que si se pueda agregar, comentame de que es porfa

**Comment by adrianVaNa** [comment]
viene del archivo edit-paciente.php, está comentado el input de expediente... Lo saca de la BD de la tabla pacientes, en todos los registros la columna expediente está en blanco

**Comment by tavorazo** [comment]
ammm, dejalo en blanco

**Comment by tavorazo** [comment]
ya lo checaste entonces_ para subirlo a su server_?
