### ISSUE TITLE
corregir api de post stickers

### ISSUE THREAD

**Issue by tavorazo** [tavorazo/Clinic#64]
corregir la API de la forma que te mencionaba para estar listos y empezar las apps nuevas

**Comment by adrianVaNa** [comment]
Corregida y subida a heroku para que la cheques 
listadetareas.herokuapp.com

**Comment by adrianVaNa** [comment]
aunque falta base de datos

**Comment by tavorazo** [comment]
en lo que quedamos el sabado sas?
