### ISSUE TITLE
mezclar bases

### ISSUE THREAD

**Issue by tavorazo** [tavorazo/Clinic#70]
base de endoperio.com.mx vs base endiperio.wbx.technology

**Comment by tavorazo** [comment]
1. checar en phpmyadmin para ver cuantos son
2. checar la base en wx.technology para comparar usuarios diferentes.


limpiar los usuarios en blanco o usuarios prueba y listar en un excel los campos en blanco.

**Comment by adrianVaNa** [comment]
ultimo usuario sincronizado: 7492
Usuarios hasta la fecha: 7622
usuarios de prueba en server endoperio: 7494, 7498-7503... 7 usuarios de prueba

**Comment by tavorazo** [comment]
explciame más a detalle porfa
