### ISSUE TITLE
Arreglar index de merca

### ISSUE THREAD

**Issue by adrianVaNa** [tavorazo/Clinic#71]
Ajustar el estilo del form

**Comment by adrianVaNa** [comment]
Ya está en position relative el form, ya hace scroll pero sigue sin ajustarse el cuadro contenedor

**Comment by tavorazo** [comment]
ok, lo checo. Gracias

**Comment by tavorazo** [comment]
sale un alert( ) en mercadotecnia

**Comment by tavorazo** [comment]
Ta etiqueta de "fecha de consulta" debe de ser "ultima consulta" 

la etiquete de semana debe ser "filtrado por semana" separado por un <hr> de lo anterior

y los Order By, dales un margin o padding a las etiquetas .

Saludos y gracias,

**Comment by tavorazo** [comment]
- Los descargables son CSV, no XML.

**Comment by tavorazo** [comment]
@adrianVaNa
