### ISSUE TITLE
agregar paciente

### ISSUE THREAD

**Issue by tavorazo** [tavorazo/Clinic#75]
si agregas numeros en el campo telefono de emergencia surge este error

10Error de consulta 4: Out of range value for column 'tel_emergencia' at row 1

**Comment by adrianVaNa** [comment]
cambié de input type=number a input type=tel... falta cambiar la columna a varchar en la base de datos... se puede hacer en phpmyadmin sin alterar los valores ya almacenados

**Comment by tavorazo** [comment]
esto ya esta?

**Comment by adrianVaNa** [comment]
falta lo de la bd nada más

**Comment by tavorazo** [comment]
okas :)

**Comment by tavorazo** [comment]
ya quedo, cierto?
