### ISSUE TITLE
Estilo a sesion

### ISSUE THREAD

**Issue by tavorazo** [tavorazo/Clinic#78]
-incluir header
-incluir Footer

-incluir class="btn" a cada input del form

**Comment by adrianVaNa** [comment]
al form de login? o a cuál form te refieres?

**Comment by adrianVaNa** [comment]
Ya incluí el header y foter al mensaje de exito/fallo de sesión

**Comment by tavorazo** [comment]
me refiero al form de pedir cita online

**Comment by tavorazo** [comment]
ya esta eso?

**Comment by adrianVaNa** [comment]
Ya le di estilo al form
