### ISSUE TITLE
Imágen en editar felicitación

### ISSUE THREAD

**Issue by adrianVaNa** [tavorazo/Clinic#81]
No aparece la imagen de felicitación en 
enviar_felicitacion_editar.php

**Comment by tavorazo** [comment]
esto ya lo estas haciendo, no?


2016-02-08 16:46 GMT-06:00 adrianVaNa <notifications@github.com>:

> No aparece la imagen de felicitación en
> enviar_felicitacion_editar.php
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tavorazo/Clinic/issues/81>.
>



--

**Comment by adrianVaNa** [comment]
La imágen se obtiene de hacer hacia este archivo... o cuál debe de ser la imagen?

**Comment by tavorazo** [comment]
si, cuando es editar felicitación es de un post en un form, la neta esas
cosas ya no le metí mano. Fue aquel pero si no, tendrías que hacerlo :(

Avisame que paso

El 26 de febrero de 2016, 19:04, adrianVaNa <notifications@github.com>
escribió:

> La imágen se obtiene de hacer hacia este archivo... o cuál debe de ser la
> imagen?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tavorazo/Clinic/issues/81#issuecomment-189543965>.
>



--
