### ISSUE TITLE
Selección de doctor para pacientes

### ISSUE THREAD

**Issue by adrianVaNa** [tavorazo/Clinic#82]
Se han estado seleccionando usuarios incorrectos como doctor para cita de pacientes. Por ejemplo: Doctor-Mercadotécnia

**Comment by tavorazo** [comment]
:( tenemos que filtrar esa consulta

2016-02-08 17:00 GMT-06:00 adrianVaNa <notifications@github.com>:

> Se han estado seleccionando usuarios incorrectos como doctor para cita de
> pacientes. Por ejemplo: Doctor-Mercadotécnia
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tavorazo/Clinic/issues/82>.
>



--
