### ISSUE TITLE
error consulta

### ISSUE THREAD

**Issue by tavorazo** [tavorazo/Clinic#9]
no jala consulta en historial nomina

**Comment by KurokiUrabe** [comment]
ya veo que no funciona jajajaja

**Comment by tavorazo** [comment]
no te entendi

**Comment by KurokiUrabe** [comment]
no se por que no funciona 
deja ver si imprimo la query

**Comment by tavorazo** [comment]
si no lo tienes en heroku no podría ayudarte jeje

**Comment by KurokiUrabe** [comment]
pues solo revisa la base de datos de la tabla nomina_historial
si esta vacía pues no esta mal la query

**Comment by tavorazo** [comment]
ya esta esta vdd?

**Comment by KurokiUrabe** [comment]
eso creo no veo mas funcionalidad y supongo que la lógica esta bien
