### ISSUE TITLE
Ajustar dirección de fotos de pacientes

### ISSUE THREAD

**Issue by adrianVaNa** [tavorazo/Clinic#92]
fotos en dirección: "pacientes/Fotos-endoperio/"

**Comment by adrianVaNa** [comment]
también ajustar dirección de fotos intra

**Comment by tavorazo** [comment]
eso lo tienes que hacer desde casa? o tienes que ir?

2016-02-23 13:34 GMT-06:00 adrianVaNa <notifications@github.com>:

> también ajustar dirección de fotos intra
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tavorazo/Clinic/issues/92#issuecomment-187859048>.
>



--

**Comment by adrianVaNa** [comment]
Desde aquí, sólo es cambiar la dirección en el PHP
